config/routes.rb
Rails.application.routes.draw do
  root 'authors#index'

  resources :authors do
    # all this does is make routes exist under authors
    # all the routes still go to the same controllers
    # e.g. /authors/:id/book still calls BooksController index method
    resources :books, only: [:show, :index]
  end

  namespace :admin do
    # this also makes a new route
    # BUT it makes the methods go to a whole new controller
    # Admin::BooksController (which it expects to be in controllers/admin/books_controller.rb)
    resources :books, except: [:show, :index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :check_auth
  private
  def check_auth
    # exercise to the reader to check auth
    Rails.logger.info("CHECKING ADMIN STATUS")
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < Admin::ApplicationController
  before_action :set_book, only: [:edit, :update, :destroy]

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to [@book.author, @book], notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to [@book.author, @book], notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    author = @book.author
    @book.destroy
    respond_to do |format|
      format.html { redirect_to author, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :genre, :author_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :main_genre, :birthday)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show]
  before_action :set_author

  # GET /books
  # GET /books.json
  def index
    if @author.present?
      @books = @author.books
    else
      @books = Book.all
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    def set_author
      # We're using find_by instead of just find here, because find
      # throws an exception if the thing is not found and in this
      # case, we won't always have an author_id, because we still have
      # the top-level book routes
      @author = Author.find_by(id: params[:author_id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/admin/books/_form.html.erb
<%= form_with(model: [:admin, book], local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>

  <div class="field">
    <%= form.label :author_id %>
    <%= form.text_field :author_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', [@book.author, @book] %> |
<%= link_to 'Back', author_books_path(author_id: @book.author.id) %>

app/views/admin/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :main_genre %>
    <%= form.text_field :main_genre %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select :birthday %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Main genre</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.main_genre %></td>
        <td><%= author.birthday %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Main genre:</strong>
  <%= @author.main_genre %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @author.birthday %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Genre</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.genre %></td>
        <td><%= link_to book.author.name, book.author %></td>
        <td><%= link_to 'Show', [@author, book] %></td>
        <td><%= link_to 'Edit', edit_admin_book_path(book) %></td>
        <td><%= link_to 'Destroy', [:admin, book], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_admin_book_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @book.genre %>
</p>

<p>
  <strong>Author:</strong>
  <%= link_to @book.author.name, @book.author %>
</p>

<%= link_to 'Edit', edit_admin_book_path(@book) %> |
<%= link_to 'Back', author_books_path(author_id: @book.author.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testfoo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>